global:
    scrape_interval: 15s

    external_labels:
        monitor: "lighthouse-docker"

scrape_configs:
    - job_name: "local-lighthouse"
      scrape_interval: 5s
      file_sd_configs:
          - files:
                - "/prometheus/targets/scrape-targets.json"
    - job_name: prometheus
      honor_timestamps: true
      scrape_interval: 15s
      scrape_timeout: 10s
      metrics_path: /metrics
      scheme: http
      follow_redirects: true
      enable_http2: true
      static_configs:
          - targets:
                - localhost:9090
