global:
    scrape_interval: 15s

    external_labels:
        monitor: "lighthouse-docker"

scrape_configs:
    - job_name: "local-consensus"
      scrape_interval: 10s
      metrics_path: /metrics
      file_sd_configs:
          - files:
                - "/prometheus/targets/consensus-targets.json"
    - job_name: "local-execution"
      scrape_interval: 10s
      metrics_path: /debug/metrics
      file_sd_configs:
          - files:
                - "/prometheus/targets/execution-targets.json"
